version: '3.1'

services:
  app:
    container_name: groupe1
    image: groupe1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - dbpostgresql

  dbpostgresql:
    container_name: groupe1-db
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./groupe1-db-data/:/var/lib/postgresql/data